#配置数据库连接池
spring:
  datasource:
#    TODO 数据库地址要改为远程ip
    url: jdbc:mysql://101.132.133.15:3306/softwarecup_zzzh?useSSL=false&useAffectedRows=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: test
  rabbitmq:
    host: 152.136.109.47
    port: 5672
    username: Admin
    password: Admin123123@
    virtual-host: /


##配置mapper的xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  `configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql`

shiro:
  ##当用户访问某个需要登录的功能时，但是被shiro内置的过滤器拦截后，判断本次请求
  ##没有登录，而是直接访问的，则重定向到loginUrl的路径资源响应给用户
  loginUrl: /login
server:
  port: 8088
  tomcat:
    accesslog:
      ipv6-canonical: true

#配置PageHelper
#标识是哪一种数据库
pagehelper:
  helperDialect: mysql
  reasonable: true  #为了使用输入页数为负或者超出最大页时候使页数为最小或最大值
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true
#log4j2配置

DotnetCapConfig:
  userName: Admin






